language: node_js
node_js:
  - "12"
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
