name: Publish to GitHub Pages

on:
  push:
    branches:
      - svelte

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies 👨🏻‍💻
        run: pnpm install

      - name: Generate static site ⚡️
        run: pnpm build

      - name: Deploy to GitHub Pages 🚀
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
          fqdn: travel.fbjorn.cc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}